version: '3'
services:
  
 gvm10:
    image: falkowich/gvm10:psql
    ports: 
      - 443:443
      - 9391:9391
    restart: always
    volumes:
      - gvm:/usr/local/var/lib/gvm/
      - psql:/var/lib/postgresql/
    environment:
      - http_proxy=
      - https_proxy=
      - RSYNC_PROXY=
      - SMTP_Host=
      - Default_Domain=
      - Adminaddr=
volumes:
  gvm:
  psql:
