version: '3'
services:
  
  gvm10:
    image: falkowich/gvm10:edge
    ports: 
      - 443:443
    restart: always
    volumes:
      - gvm:/usr/local/var/lib/gvm/
    environment:
      - http_proxy=
      - https_proxy=
      - RSYNC_PROXY=
      - SMTP_Host=
      - Default_Domain=
      - Adminaddr=
volumes:
  gvm:
